[package]
name = "region-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
time = "0.3.44"
whoami = "2.0.1"
flate2 = { version = "1.1.8", features = ["zlib-rs"] }
sysinfo = "0.38.1"
common-rs = { path = "../common-rs" }

[lib]
crate-type = ["cdylib"]